services:
  db:
    image: 'url_shortener:latest'
    container_name: url_shortener
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener
    ports:
      - "3306:3306"