services:
  db:
    image: mysql:latest
    restart: always
    container_name: url_shortener_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener
    ports:
      - "3306:3306"